repo_url: "https://github.com/harishmsgit/TravelMemory.git"
app_user: "ubuntu"
app_dir: "/home/ubuntu/travelmemory"
backend_port: 3001
frontend_port: 80
# MongoDB Atlas Configuration
mongo_uri: "mongodb+srv://senharishms108:BhmebRock%21@atlas-cluster-harish-27-11-2025.mongodb.net/travelmemory?retryWrites=true&w=majority"
