repo_url: "https://github.com/harishmsgit/TravelMemory.git"
app_user: "ubuntu"
app_dir: "/home/ubuntu/travelmemory"
backend_port: 3001
frontend_port: 80
# MongoDB EC2 host in the same VPC/private subnet
mongo_uri: "mongodb://172.31.43.42:27017/travelmemory"
