repo_url: "https://github.com/harishmsgit/TravelMemory.git"
app_user: "ubuntu"
app_dir: "/home/ubuntu/travelmemory"
backend_port: 3001
frontend_port: 80
mongo_db_name: "travelmemory"
mongo_app_user: "traveladmin"
mongo_app_password: "ChangeMe123!"
mongo_root_user: "admin"
mongo_root_password: "ChangeMeRoot123!"
mongodb_port: 27017
mongo_uri: "mongodb+srv://senharishms108:BtnHurryPot@26@atlas-cluster-harish-27.7gyzfqt.mongodb.net/travelmemory?retryWrites=true&w=majority"
